version: '3'

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"  # Map host port 8080 to container port 80
    volumes:
      - ./src:/var/www/html  # Mount your PHP application directory into the container